### ISSUE TITLE
SingleOrNone should throw and exception when more than one item is present in collection

### ISSUE THREAD

**Issue by Euphoric** [nlkl/Optional#41] opened 2017-11-01 10:02 UTC
The standard behavior of `SingleOrDefault()` in Linq is that it throws an exception when more than one value is in the `IEnumerable`. This is expected behavior, as it can be used to guarantee there is only single item. And this is also what makes it different from `FirstOrDefault()`.

I would expect exactly same behavior in `SingleOrNone()`.

**Comment by nlkl** [comment] 2017-11-03 18:27
Hi,

It is correct that the functionality of `SingleOrNone()` differs slightly from `SingleOrDefault()`. This is, however, by design, and there are a few reasons for this.

`SingleOrNone()` promises to be a safer and more strongly typed alternative to `SingleOrDefault()`. There is an inherent tradeoff between staying consistent with `SingleOrDefault()`, which throws an exception when the count exceeds 1, or actually handling the case more safely - due to the design goals, Optional takes the safer route and handles zero and multiple elements identically: returning None.

One might argue that stying consistent with `SingleOrDefault()` would make more sense, as it actually makes it possible to distinguish between the cases where count = 0 and count > 1. I don't care much for this argument, for multiple reason:

1. The API of `SingleOrDefault()` is broken - I have lost count of how many times newcomers have expected to receive a null value, but instead seen things blow up due to an exception being thrown. More "informative" or not, this is bad API design, and replicating broken design is a bad idea, even if people are used to it.
1. This extra information is rarely needed in practice, and can easily be recovered with a call to `Any()`.
2. `SingleOrNone()` is consistent with the design of `Single()`, which handles count = 0 and count > 1 identically (unless you actually go and inspect the textual error messages).

Finally, `SingleOrNone()` does behave differently from `FirstOrNone()`, as the former returns None when the count exceeds 1, which is not the case for the latter.

I hope it explains things.

Best regards,
Nils

**Comment by Euphoric** [comment] 2017-11-05 07:35
Thanks for your clarification.

I disagree with `SingleOrDefault`'s API being broken. Exceptions are valid way to handle exceptional states and, from my perspective, `SingleOrDefault`'s primary use-case is to ensure that there are no more than one (or zero) items. Any more would be considered invalid or exceptional state, and should be treated as an bug in code. At least, that is how I always use it. Every time I used it, I always treated "no items" and "more than one item" to be different as different cases. And most of the time, "more than one item" was non-recoverable, exceptional state.

As for your reasons:

1. I can't tell if this is true or false, as I have no experiences with that. But I would argue that your change of `SingleOrNone`'s API introduced exactly same problem for people moving from Linq. Which is exactly what happened to me and what prompted me to create this issue. And I believe this is much worse problem than novices not understanding the API.

1. I disagree. If I don't need `SingleOrDefault`'s information about multiple items, then I would use `FirstOrDefault`. Usage of `Any` also ignores optimizations and multiple enumerations of enumerable.

1. This is exactly about what I said above. With `Single`, no-item is exceptional state, which indicates more of a bug in code, than state to be handled by calling code.

Maybe the way to handle this is to return `Option<T, TException>`. Then, use #42 to throw the exception.

If I could say my opinion on this topic, I believe your decision is made primarily by dislike of exceptions than any other reason.

Thanks,
Euphoric

**Comment by desarrollo03TR** [comment] 2018-05-31 00:33
> SingleOrDefault's primary use-case is to ensure that there are no more than one (or zero) items.

None = the case when InvalidOperationException is thrown, that's mean, a result of None means htere are zero o more than 1 items. If you want the information from Single you can create your own extension method.

**Comment by nlkl** [comment] 2019-09-11 10:17
Closing is this is not currently planned for Optional.

**Closed by nlkl** 2019-09-11 10:17 UTC
