### ISSUE TITLE
ValueOrFailure with specified exception.

### ISSUE THREAD

**Issue by shtse8** [nlkl/Optional#57] opened 2018-08-09 23:25 UTC
Since Nullable cannot support class type, I am now using Option to design my apis.

How do I return a value if it exists otherwise throw a specified exception?

For now we have two overloads:
```c#
// When imported, values can be retrieved unsafely as:

var value = option.ValueOrFailure();
var anotherValue = option.ValueOrFailure("An error message"); 
```

We can specify the error message, but cannot specify the specified exception.

To achieve this, I am now using:
```c#
var value = option.ValueOr(() => throw new CustomException());
```

But I think this is something like a hack. 

My expected:
```c#
var value = option.ValueOrFailure(() => new CustomException());
// Or
var value = option.ValueOrFailure<CustomException>();
```

This one makes more sense and same as other failure. Any ideas?

**Comment by nlkl** [comment] 2018-08-10 16:17
Hi @shtse8 

Actually, `option.ValueOr(() => thow new CustomException())` is the recommended approach for throwing custom exceptions (and the one I also use myself, when `ValueOrFailure()` isn't good enough).

`ValueOrFailure()` was intended as a low ceremony assertion that a value exists, e.g. for cases where `HasValue` has already been checked etc.

Although I definitely have considered supporting custom exceptions in `ValueOrFailure()` I ended up deciding against it for the following reasons:

Something like `option.ValueOrFailure(() => new CustomException())`, is syntactically so close to simply using a throw expression in `ValueOr()` (and even tad longer to type out), that it doesn't really make a huge difference i practice. Even if we did introduce it, it would still be possible to use the throw expression instead, and we then end up with two almost identical ways to do the same thing. Since what we need is already supported using standard C# features, I don't see an urgent need to introduce an extra abstraction for this.

If we, on the other hand, chose a syntax like `option.ValueOrFailure<CustomException>()` we would have a more lightweight way to do the same, which would be quite nice. However, there is no guarantee that we have an empty constructor available, and there is no easy way to provide relevant parameters to any non-empty constructor. We could have an overload that took something like `params object[]` as input, and used reflection to fill in the parameters, but my hypothesis is that people would still prefer the `ValueOr()` approach, since you get better type safety and intellisense when filling in the constructor parameters, etc.

Hope that clarifies things a bit - but feel free to bring up some counter-arguments, and I might reconsider 🙂 

/ Nils

**Comment by shtse8** [comment] 2018-08-11 04:26
Thanks for your explanation. I agree with your consideration. However, I would recommend putting it as an example as you say `option.ValueOr(() => thow new CustomException())` is the recommended approach for throwing custom exceptions. For my first time, I spent lots of time for finding out how to do it and what is the best approach to do it.

**Comment by nlkl** [comment] 2018-12-12 21:40
Very good point. I have added it to the develop readme, so it will show up as soon as release v4.1.0.

Closing this issue for now.

**Closed as completed by nlkl** 2018-12-12 21:40 UTC
