### ISSUE TITLE
Option Constructor?

### ISSUE THREAD

**Issue by 16bytes** [nlkl/Optional#14] opened 2016-12-07 13:44 UTC
I've read the documentation, and what I don't currently see is a convenient way to construct an Option from a value.

This would be convenient for wrapping calls to other APIs that don't use options.  For example

`var x = Option.From(MyOperation());`

`x` in this case would be Some() if MyOption() returned a non-null value, and None otherwise.

Possible implementation would be 

```
static public Option<T> OptionFrom<T>(T value)
{
  return value == null ? Option.Some(value) : Option.None<T>();
}
```

This would be similar to `Option(x)` works in [Scala](http://www.scala-lang.org/api/2.12.0-RC2/scala/Option$.html#apply[A](x:A):Option[A]).

**Comment by nlkl** [comment] 2016-12-07 17:12
Hi,

Actually, the operation you mention is called `SomeNotNull` in Optional, and is available as an extension method:

```csharp
var option = myValue.SomeNotNull();
```

Optional intentionally has a very explicit name for this operation. Although filtering on null is typically "the right thing to do", it is actually less obvious that it should be the default behavior, when considering things such as nullables and value types.

Hope it help.

- Nils

**Comment by 16bytes** [comment] 2016-12-07 18:44
Thanks.  I did see `SomeNotNull`, but it wasn't obvious to me that this returns `None` when null and `Some` otherwise.  Wouldn't `ToOption` make this more clear and reflect the nullables extensions of the same name?

> Although filtering on null is typically "the right thing to do", it is actually less obvious that it should be the default behavior

Can you explain the rationale here?  A Option wraps a value or nothing.  When mapping between Options and APIs that contain nulls, isn't it obvious that all null values should be treated as `None`?

I was also confused by this related bit on the readme: 

> Note that it is also allowed (but hardly recommended) to wrap null values in an Option instance.

Is there a use-case behind this or a reason that Options can't be guaranteed null-safe?  If you can shove null into `Some` doesn't that defeat the purpose of Options in the first place?  I understand there may be API edge cases around nullables and value types, but null-tests are unambiguous, so I miss why null wouldn't always map to `None` and `Some` be statically guaranteed to be non-null.

Thanks in advance for the clarification.

**Comment by nlkl** [comment] 2016-12-07 23:11
I actually did consider having an overload of `ToOption()` instead of `SomeNotNull()` at several points. 

The reason for having a `ToOption()` method for nullables, is that they are conceptually very similar to options, in that a `Nullable<T>` is an explicit container, with zero or one element.

The reason `SomeNotNull()` has a distinct name, is actually a consequence of the rationale for not having `SomeNotNull()` be the default behavior. Let me elaborate.

In C#, nulls are represented as a value, and not a container. Any implementation of option types in C# need to make the decision, whether nulls should be treated as just that, a value, or be a special case that is never allowed inside an option.

There are upsides and downsides to both approaches. I have listed a few of these considerations below:

### 1) Complexity

Null filtering would result in a more complex library, due to handling of such special cases. Specifically, this would need to be taken into account, not just when creating options, but also during any transforming operation such as `Map`. Further, in this case one might also want similar special case handling for nullables, again increasing the complexity. Nevertheless, one might argue that it could still be worth it, in case this complexity was kept inside the library only.

### 2) Consistent behavior

If null is treated like any other value, options are generally more well-behaved. This is very subtle, and I don't want to pull the Monad-argument, so I will give a concrete example below.

Consider the following refactoring:

```csharp
val.Some().Map(v => Mapping(v))
// ===> 
Mapping(val).Some();
```

Intuitively, one would expect these to be the same: Putting a seed in a pot and letting it sprout, should not be different from letting the seed sprout, and then only afterwards putting it in the pot. We would like to think of `.Some()` as "putting something into a container".

However, this reasoning might break down if we filter nulls (in this case shown using `SomeNotNull`):

```csharp
string val = null;
val.Some().Map(v => v ?? "alternative") // => Some("alternative")
val.SomeNotNull().Map(v => v ?? "alternative") => // None
// ===> 
Mapping(val ?? "alternative").Some(); // => Some("alternative")
Mapping(val ?? "alternative").SomeNotNull(); // => Some("alternative")
```

As you can see, the null filtering introduces a semantic difference between the two. Certainly, this example is rather trivial, and of limited utility. But there are several of those small and subtle differences, that make it more difficult to freely compose operations on options, when nulls are automatically filtered.

Being explicit avoids much of the confusion.

### 3) Filtering nulls is of limited use

If we were to sacrifice 1) and 2), and automatically filter away nulls, we would at least want to get some real value in return. However, although we might seem to get extra safety at first glance, the reality is actually a bit more blurred. 

The sad truth is that nulls are everywhere - or at least can be everywhere. This is not something option types can fix*. After all, most values will not be wrapped in an option, so removing the possibility of nulls inside an option doesn't remove the possibility of nulls everywhere else. We would slightly decrease the risk of null-reference exceptions _caused by options_, but this already happens very rarely compared to all the null-ref exceptions thrown everywhere else.

Secondly, the null check would be shallow, so whereas we could avoid a null-reference exception from the following:

```csharp
potentiallyNull.Some().Map(v => v.Length)
```

it could still blow up on nested properties:

```csharp
option.Map(x => x.SomePropertyThatCanBeNull.Length)
```

Based on this, automatic filtering of nulls has too little utility, in my opinion, to be worth the sacrifice of 1) and 2).

*) Note, however, that options do improve the situation, just in a different way. By providing an explicit type to represent "nullability", Optional makes it possible to heavily cut down on the actual amount of null values in your code - and as you cut down on the amount of null values, so do you cut down on the amount of null-reference exceptions. Further, as options are explicit in the type signature of a method, you can, if you are using Optional consistently in your internal API's, handle nulls much more pessimistically (e.g. just throwing ArgumentNullExceptions and so on), as you never need to consider if a null value is an error or a valid representation of an absent value - in my experience, this makes null checking quite a bit less frustrating and error prone.

### Summary

So, to summarize, I decided against the special case handling of nulls, and Optional treats a null value as any other value.

Of course, filtering away nulls is still a very common requirement, and typically one of the most commonly used operations when working with Optional. That is why we have a few convenience methods, to explicitly handle this use case:

```csharp
return email
    .SomeNotNull() // Wraps a value and filters away nulls
    .Map(e => GetUserByEmail(e))
    .NotNull() // Filters away nulls that are already wrapped 
```

If we briefly return to the `ToOption()` method, I hope I have outlined what I consider the conceptual difference between null values (just a value) and nullables (a container, `Nullable<T>`, like options), as seen from the point of view of Optional at least.

Even so, I still regularly consider introducing the `ToOption()` method for reference types. However, it would either be a duplicate method (identical to `SomeNotNull`), that as an extension method would pollute intellisense on all reference types, or a breaking change (if `SomeNotNull` were to be removed). Due to this, I still need a bit more convincing before adding it.

Sorry for the rather long-winded answer - I hope it touched upon at least some of your concerns. Feel free to ask if something is unclear or doesn't make any sense :)

**Comment by 16bytes** [comment] 2016-12-08 14:38
Thanks for such a long and detailed response!

> Even so, I still regularly consider introducing the ToOption() method for reference types.

I would suggest a new non-extension static method on Option as an alternative.  That way it's easy to see how to get a `Some`, `None` or wrap an existing value.  Personally I find this easier to read:

`Option.ToOption(email).Map(e=>GetUserByEmail(e))`

Also, some people may not like the extension methods on every reference type.  I would vote for making all of the functionality available without using extension methods.  So, if you are using a static import, it gets even cleaner:

`ToOption(email).Map(e=>GetUserByEmail(e))`

Even if you call `ToOption` `SomeNotNull`.

> So, to summarize, I decided against the special case handling of nulls, and Optional treats a null value as any other value.

This is reasonable.  I still assert that `Some(null)` is quite weird--Scala also allows this because of the JVM--but until there's support at the IL level, it's probably not worth trying to gate out nulls from `Some`s.

**Comment by nlkl** [comment] 2016-12-08 21:27
Adding a new static method to `Option` could be an idea - I will give it some thought.

I certainly agree that there are some advantages to regular static methods, over extension methods, in that they don't pollute intellisense. When Optional was first released, static imports were not yet available, and using extension methods was the best way to reduce verbosity when working with options.

Now that static imports are available, this could be a viable alternative to using extension methods. However, I still tend to prefer the ease of using extension methods, as it "flows" a bit more nicely when typing out your code. Polluting intellisense, after all, also means that intellisense is readily available when working with options.

Nevertheless, this is of course a matter of preference, and highly subjective. In case you would like to try it out, you could probably hide the extension methods by not importing the Optional namespace, and then define your own custom static `Option` class with the functionality you need (just forwarding to the extension methods most likely).

Regarding the final observation (about Scala), I actually believe that most functional programming languages running on .NET or the JVM would allow nulls, as such languages are typically quite theoretically rooted (and would like option types to be monads, which requires treating nulls as values). This also includes F# on the .NET side. Java's optional is probably the one major example of the opposite design, where nulls are not allowed.

**Comment by nlkl** [comment] 2016-12-23 08:32
I will close this issue for now. Feel free to open another issue for further clarification.

**Closed by nlkl** 2016-12-23 08:32 UTC
