### ISSUE TITLE
Should .Map return None if mapping returns null?

### ISSUE THREAD

**Issue by JudahGabriel** [nlkl/Optional#34] opened 2017-08-25 22:26 UTC
I was surprised by this behavior:

    var obj = new { ThisIsNull = (string)null };
    var result = Option.Some(obj)
           .Map(o => o.ThisIsNull)
           .ValueOr("hello");

Expected: "hello"
Actual: null

Isn't this unintuitive behavior? Looking at Java 8's [Optional<T>](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#map-java.util.function.Function-) and Rust's [std::Option](https://doc.rust-lang.org/std/option/enum.Option.html#examples-8), the result of .Map is None if the mapping produces null.

I realize we can get this functionality with .Map(...).NotNull(), however, the existing behavior remains unintuitive. Thoughts?

**Comment by nlkl** [comment] 2017-08-27 10:43
Hi,

This is actually by design. You can find some more details here: https://github.com/nlkl/Optional/issues/14

The argument basically boils down to optionals behaving consistently under refactorings (the Monad argument), and the unfavorable "value/complexity ratio" of introducing a special case for nulls.

It is true that Java disallows null inside an Optional. Rust, however, doesn't really have the concept of null, so it cannot be directly compared. A more direct comparison would be with Scala and F#, which both allows nulls inside an Option.

/Nils

**Comment by JudahGabriel** [comment] 2017-08-28 21:06
Your documentation and your reasoning are quite clear-headed! I figured it was a deliberate design choice.

Let me see if I understand your reasoning for this decision:

1. Filtering nulls in the library will introduce complexity into the library itself.
2. Consistency; inverted operations would no longer return the same result. val.Some().Map(mapping) != mapping(val).Some().
3. Doesn't solve all cases of null: users can still make null happen given .Chaining.Null.Value.

If I understand you right, I'm still in favor of filtering nulls. To respond to the above:

1. True! But we users don't care about _your_ complexity. We care about making our code simpler. :-) The library filtering out nulls makes _our_ code simpler.
2. The consistency argument doesn't matter to me. I've never thought, "Gee, I wonder if changing the order of operation here will affect the output" - rather, my intuitive expectation is that yes, the output may change if the order changes. This is a non-issue to me.
3. Just because we can't fix the world doesn't mean we can't make it a little better. :-) As a user, I would not expect .Chaining.Null.Values to work. But I would expect .Map(o => o.NullVal) to be None.

Overriding these is the surprising behavior of allowing nulls into an Option, and "lying" that .HasValue is true. That's unintuitive as a user, particularly for a library intended to deal with the problem of null values.

That's my feedback. This is a great library, and I'll still use it regardless. :+1:

**Comment by nlkl** [comment] 2020-04-28 06:48
Closing this one for now. Feel free to re-open or open a new issue, if something pops up.

**Closed by nlkl** 2020-04-28 06:48 UTC
